[features]
resolution = true
skip-lint = false

# 重启本地`solana-test-validator -r`后，下面的programid会重新生成，要重新改成新的
# 通过make keys可以看真是的programid
# 更改对应program里面的 declare_id!("4ALfWS4aWMCrCUbnLAjUafVeREZDoGYMErNgv2LZ8T9U");
# 改完之后 重新 `make build make dploy`，才能测试`make test`
[programs.localnet]
counter_anchor = "iy7pJEc7gEJRjj4LgMNSbiVYGRh8ufZQtTEvnYvj5ow"
demoanchor = "7hRaTZTmGhfFrTGGQND8XWFNBiMdf1xu3eYbbYGzeqKG"
fight = "HF6biQrNj8PjfL675LzobDiyZB5venfriJMF5pPF6L9Z"
p2 = "H24Tt2U2K5wdnBXNzthSVqfc1i1CkWhtJ3YbyNM7p1xA"
puppet = "6YxFEzVTnsV78efnXZeAkJt2pZpad66rVgbTM1Hxyukz"
rent = "7gUT8ZTgtzMMydSwWVN56pPnFGA2k8QoAtmKJT89NgQ3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
demo = "pwd && echo 执行这个脚本 "
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
