[toolchain]

[features]
resolution = true
skip-lint = false

# 重启本地`solana-test-validator -r`后，下面的programid会重新生成，要重新改成新的
# 通过make keys可以看真是的programid
# 更改对应program里面的 declare_id!("4ALfWS4aWMCrCUbnLAjUafVeREZDoGYMErNgv2LZ8T9U");
# 改完之后 重新 `make build make dploy`，才能测试`make test`
[programs.localnet]
counter_anchor = "EeRX3JoSdTXcRAS5JBHxuVpXWGKKNckSt42nBJQynKW3"
demoanchor = "9H38cHGSZirSQhQbjhvariRUoqPB4fRZJWs5kydhsepa"
p2 = "3EYNaRt9Sg33bEMLBhCajeadTmmhCJ8n4UybcNEM1Jfa"
puppet = "4ALfWS4aWMCrCUbnLAjUafVeREZDoGYMErNgv2LZ8T9U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
demo = "pwd && echo 执行这个脚本 "
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
