[toolchain]

[features]
resolution = true
skip-lint = false

# 重启本地`solana-test-validator -r`后，下面的programid会重新生成，要重新改成新的
# 通过make keys可以看真是的programid
# 更改对应program里面的 declare_id!("4ALfWS4aWMCrCUbnLAjUafVeREZDoGYMErNgv2LZ8T9U");
# 改完之后 重新 `make build make dploy`，才能测试`make test`
[programs.localnet]
counter_anchor = "FNUySs7U7vhGEGJp7gykVnrTF7ADc9JdWmQN8DTTFVRo"
cpi_invoke_signed = "GpzQusdyzEKgKL7frLgaNSmuLW8he5TbrRneLnqtBGHT"
demoanchor = "H3PTiZJrKv2RKP2K5KXaFH7JDKjScYBUDHcyTSUXzB9d"
fight = "AQaCjYKWP1ei1dd6BwTU1CpMWngv2b2kx3e9mgikNGwG"
p2 = "DhKPkbWWP8WCg71aesxWG9DVWn5JhUbADuEU177s5oA"
puppet = "6hbdXkgoEHtpyaBYpqZQBfKpgujCANdg5pVBdPjLfyEn"
puppet-master = "AY6YPi18PCdCn9bBHceCk6893bMuqeUph6SWrvhuo45Q"
rent = "S6xBYpYTUn8LaAbG32dqMhWTyG647TLHBWnE1NLreNz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
demo = "pwd && echo 执行这个脚本 "
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
# Adds a directory where you want the <idl>.ts file to be copied when running anchor build. This is helpful when you want to keep this
# file in version control, like when using it on the frontend, which will probably not have access to the target directory generated byanchor.
types = "app/src/idl/"